---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r, include = F}
library(tidyverse)
library(purrr)
```
The classes:
1. Sequence
2. W_Sequence
3. Sequence_Itemset
4. W_Sequence_itemset
5. Sequence_List, Aggregated_Data


```{r}
inp <- read_csv("./data/inp.csv")
t10 <- read_csv("./data/t10.csv", col_names = c("id", "period", "event"), skip = 1, n_max = 350)

(inp2 <-
  inp %>%
  aggregate_sequences(format = "%Y-%m-%d") %>%
  get_weighted_sequence())

t10 %>%
get_weighted_sequence() %>%
  unclass()

t10 %>%
summarise(seq = . %>% get_weighted_sequence() %>% list(.))

ids <- unique(t10$id) 


inp2$sequence
str(inp2$sequence)
get_weighted_sequence(inp2$sequence)

inter_sequence_distance(inp2$sequence[[1]],inp2$sequence[[2]]) 

wseq_1 <- align_sequences(inp2$sequence[[1]],inp2$sequence[[2]]) 

inter_sequence_distance(wseq_1, inp2$sequence[[2]])

```

```{r}
t10 <- read_csv("./data/t10.csv", col_names = c("id", "period", "event"), skip = 1, n_max = 350)


cluster_knn <- function(df){
  set.seed(1)
  ids <- unique(df$id)
  clust <- sample(1:3, length(ids), replace = T)
  density <- abs(rnorm(length(ids), 1, 3))
  cluster_info <- tibble(id = ids, cluster = clust, density = density)
  df %>%
    left_join(cluster_info, by = "id") %>%
      group_by(cluster) %>%
        arrange(density,id) %>%
          select(-density)
}



t10 %>%
  pre_aggregated() %>%
  cluster_knn() %>%
    mutate(n = map_int(df_list, nrow)) %>% 
    mutate(weighted_seq = map(df_list, get_weighted_sequence))

(x <- 
  t10 %>%
  pre_aggregated() %>%
  cluster_knn() %>%
    mutate(n = map_int(df_list, nrow)) %>%
      .$df_list %>% .[[3]])

get_weighted_sequence(x)
# t10 %>%
#   get_weighted_sequence() %>% 
#   class()
# 
# t10 %>% 
# summarise(seq = list(. %>% get_weighted_sequence()))
```

