# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
calculate_sorenson_distance_cpp <- function(itemset_1, itemset_2, weight, dict) {
    .Call('_approxmapR_calculate_sorenson_distance_cpp', PACKAGE = 'approxmapR', itemset_1, itemset_2, weight, dict)
}

#' @export
dist_bw_sequences_cpp <- function(sequence_1, sequence_2, weight, dict) {
    .Call('_approxmapR_dist_bw_sequences_cpp', PACKAGE = 'approxmapR', sequence_1, sequence_2, weight, dict)
}

#' @export
inter_sequence_distance_cpp <- function(sequences, weight, dict) {
    .Call('_approxmapR_inter_sequence_distance_cpp', PACKAGE = 'approxmapR', sequences, weight, dict)
}

